// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGUy9dQJ--voPcCC6xR7ju1jkiMSasgVk',
    appId: '1:365884810939:web:6ee3b97c170791bfd46b9e',
    messagingSenderId: '365884810939',
    projectId: 'ai-travel-platform',
    authDomain: 'ai-travel-platform.firebaseapp.com',
    storageBucket: 'ai-travel-platform.firebasestorage.app',
    measurementId: 'G-90BM3CPFY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpK_CI5vlRvzWOcOWPGvCWbstdJU6SkvQ',
    appId: '1:365884810939:android:e7047a60b859b5ccd46b9e',
    messagingSenderId: '365884810939',
    projectId: 'ai-travel-platform',
    storageBucket: 'ai-travel-platform.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGUy9dQJ--voPcCC6xR7ju1jkiMSasgVk',
    appId: '1:365884810939:web:59e0d801c4fd0c8cd46b9e',
    messagingSenderId: '365884810939',
    projectId: 'ai-travel-platform',
    authDomain: 'ai-travel-platform.firebaseapp.com',
    storageBucket: 'ai-travel-platform.firebasestorage.app',
    measurementId: 'G-F98R4K2X5R',
  );
}
